# Generated by Django 4.2.3 on 2023-07-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_mentor_preferred_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
