# Generated by Django 4.2.3 on 2023-07-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_rename_hybrid_club_hybrid_link_club_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='active',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
